nodeLinker: node-modules
pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-3.3.1.cjs

packageExtensions:
  "@swc/jest@*":
    dependencies:
      "@swc/core": "*"
  stylelint@*:
    peerDependencies:
      "@stylelint/postcss-css-in-js": "*"
      "postcss": "*"
