name: Automated Code Review
on:
  push:
    branches:
      - '*'
      - '**/*'
      - '!main'
      - '!develop'
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --immutable
      - uses: actions/cache@v3
        with:
          path: |
            .yarn
            node_modules
          key: ${{ runner.os }}-${{ github.run_number }}
  lint:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: |
            .yarn
            node_modules
          key: ${{ runner.os }}-${{ github.run_number }}
      - run: yarn install --immutable
      - run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: |
            .yarn
            node_modules
          key: ${{ runner.os }}-${{ github.run_number }}
      - run: yarn install --immutable
      - run: yarn test
        env:
          CI: true
  build:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: |
            .yarn
            node_modules
          key: ${{ runner.os }}-${{ github.run_number }}
      - run: yarn install --immutable
      - run: yarn build
